// Category options generated by chat-gpt
// metearazz



function GenerateIdea() {
    // Options for Environment
    const environments = [
  "Ancient Forest",
  "Futuristic City",
  "Underground Cave System",
  "Island Paradise",
  "Haunted Mansion",
  "Cyberpunk Megacity",
  "Magical Kingdom",
  "Mars Colony",
  "Steampunk Sky City",
  "Ocean",
  "Forest",
  "Castle"
];

    // Options for Goal
    const goals = [
  "Retrieve the Lost Artifact",
  "Survive the Zombie Apocalypse",
  "Conquer the Galaxy",
  "Solve the Mystery",
  "Build a Time Machine",
  "Establish World Peace",
  "Create a Utopian Society",
  "Escape from a Parallel Dimension",
  "Become the Ultimate Wizard",
  "Discover a New Civilization"
];

    // Options for Genre
    const genres = [
  "Action",
  "Adventure",
  "Strategy",
  "RPG (Role-Playing Game)",
  "Simulation",
  "Puzzle",
  "Stealth",
  "Survival",
  "Horror",
  "Sports"
];

    // Options for Rule
    const rules = [
  "No Gravity",
  "Time Travel Allowed",
  "Limited Resources",
  "Dynamic Weather Changes",
  "Permadeath for Characters",
  "Random Events",
  "Infinite Levels",
  "Player-Driven Economy",
  "Procedurally Generated World",
  "Real-time Day-Night Cycle"
];

    // Options for Wildcard
    const wildcards = [
  "Players Can Only Communicate in Emojis",
  "Randomly Swapping Character Abilities",
  "Gravity Reversal at Intervals",
  "Characters Speak in Riddles",
  "Players Control Each Other's Characters",
  "Night Vision Only",
  "No Text or Speech Communication",
  "Parallel Universes Collide",
  "Players Can Rewind Time Once",
  "Limited Vision – Play in the Dark"
];

  let indexEnvs = Math.floor(Math.random() * environments.length);
  let indexGoals = Math.floor(Math.random() * goals.length);
  let indexGenres = Math.floor(Math.random() * genres.length);
  let indexRules = Math.floor(Math.random() * rules.length);
  let indexWildcards = Math.floor(Math.random() * wildcards.length);
  
  let chosenEnv = environments[indexEnvs];
  let chosenGoals = goals[indexGoals];
  let chosenGenres = genres[indexGenres];
  let chosenRules = rules[indexRules];
  let chosenWildcards = wildcards[indexWildcards];
  
  console.log(`Here is your game idea:
  Environment: ${chosenEnv}
  Goal: ${chosenGoals}
  Genre: ${chosenGenres}
  Rule: ${chosenRules}
  Wildcard: ${chosenWildcards}
  `);
}

GenerateIdea();